language: scala
scala:
  - "2.11.4"
jdk:
  - oraclejdk8

env:
  global:
    - secure: "adngy4wHe+DLnkLW0K7S8KFe+GR2mTMHx3VPs4YFooXSkJlRZMzhMzd2nJN0VNb2U7zkIrtLvsykLGIaeKF3u02iheHt3RCpRoKmxOjAkFXSRm6V7Z1J+EMVHqAG/72L2P2KkjJEaXrQqE3yG6e6elRk+qp2V3zKpQ6E5sS/g3c="
    - secure: "fjMyfWi+UndcsT+Voqxt1NVvIbqPKwDzipxK18zd+eEgASam+L4fgtmDsIXjbgdBaTX59w+Q1DNnAOT7x34XpneU+GDASDmoNdj6oCoZOHiQb/odu2WOBWf/iINCTpJtPMMr8cLQaQ3CsnSyOojaJiFERDMcO9i58kDfU1gXa/4="
env:
  - NODE_VERSION=0.12

install:
  - nvm install $NODE_VERSION

before_script:
  - sudo chmod +x /usr/local/bin/sbt

script:
  - nvm use $NODE_VERSION
  - git clone https://github.com/storm-enroute/dev-tools.git ~/.dev-tools
  - ~/.dev-tools/lint -p .
  - sbt scalastyle
  - sbt test

branches:
  only:
    - master

notifications:
  slack: storm-enroute:GnbA8DEy3mL3Pyp3cbptr7F2
